### ISSUE TITLE
数据表interface_header的default_value字段限定长度错误

### ISSUE THREAD

**Issue by cnHuaShao** [NEIAPI/nei#15]
**Bug 描述**
default_value字段预设255字节，会报错
ER_DATA_TOO_LONG: Data too long for column 'default_value' at row 1

**重现步骤**
1. 接口使用请求头Authorization时，其默认值会超过255字节

**期望结果**
初始部署SQL修改该表中字段限定为500字节

**Comment by huntbao** [comment]
可以按需修改
