### ISSUE TITLE
Debian 10.6全局安装nej成功后，使用nej命令报错:  nej: not found

### ISSUE THREAD

**Issue by mario0723** [NEIAPI/nei#26]
![image](https://user-images.githubusercontent.com/70555776/118605059-6fbec100-b7e8-11eb-9deb-9b6fe623934a.png)
安装过程没有报错

**Comment by huntbao** [comment]
nej 是这个包：https://www.npmjs.com/package/nej

所以，是安装的包不对。这个问题确实偶尔会出现，请检查一下 npm 的 regsitry 是否正确，或者更换为淘宝的 registry 试试：

```bash
npm install nej -g --registry=https://registry.npm.taobao.org
