### ISSUE TITLE
接口导入私有化项目后数据数组和Object数据结构错误

### ISSUE THREAD

**Issue by 738548439** [NEIAPI/nei#28]
**Bug 描述**
接口返回数组嵌套Object类型，导入私有化项目时结构变为哈希类型
原结构：
[{"id":"59032","name":"cY3DR6HHzm"},{"id":"59092","name":"x1iApFKWf7"},{"id":"59410","name":"9iwzKMvnGt"}]

**截图**
![image](https://user-images.githubusercontent.com/8428317/118770446-e8d71a80-b8b3-11eb-8fc7-508fe98add48.png)

**Comment by huntbao** [comment]
已修复，麻烦再试一下

**Comment by 738548439** [comment]
可以了
