### ISSUE TITLE
项目运行后, 有管理员账户吗?

### ISSUE THREAD

**Issue by cys-home** [NEIAPI/nei#36]
您好, 我想问一下, 用docker部署项目后, 在mysql的user表中, 看到有一个admin初始账户, 但是没有密码, 只能注册新账户进行登录
想问一下.
这个项目有管理员账户吗, 是怎么登录的呢?

**Comment by huntbao** [comment]
没有管理员账号，这个admin初始账号是备用的。

登录逻辑需要自己实现
