### ISSUE TITLE
本地部署登录无响应

### ISSUE THREAD

**Issue by xingxuan0819** [NEIAPI/nei#37]
**Bug 描述**
使用源码打包，npm run dev 登录无响应
代码执行到yield this.next();就没有返回了，接口一直处于pending状态

**重现步骤**

**期望结果**
正常登录

**截图**
![image](https://user-images.githubusercontent.com/58974233/137267423-bdfbe712-0a68-4fb6-a2d0-5845646a2875.png)

**软件环境**
 - 操作系统及版本:mac
 - Node及版本: v14.18.0
 - 浏览器及版本: chrome

**其他信息**
其他信息可以填这里。

**Comment by huntbao** [comment]
登录功能需要自己实现
